import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const ProtectedPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Protected Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Protected Page</h1>
    </div>
  )
}

export default ProtectedPage
